[package]
name = "bkernel"
version = "0.0.1"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]
build = "build.rs"

[lib]
name = "kernel"
path = "src/kernel.rs"
crate-type = ["staticlib"]
doctest = true

[dependencies.stm32f4]
path = "./stm32f4"

[dependencies.smalloc]
path = "./smalloc"

[dependencies.linkmem]
path = "./linkmem"

[dependencies.bscheduler]
path = "./bscheduler"

[profile.release]
opt-level = 3
lto = true
debug = true
debug-assertions = false
